apiVersion: 1

groups:
  - orgId: 1
    name: M@LINTIC
    folder: M@LINTIC
    interval: 1m
    rules:
      - uid: malintic-target-down
        title: Cible Prometheus indisponible
        condition: C
        for: 2m
        noDataState: NoData
        execErrState: Error
        labels:
          severity: critical
        annotations:
          summary: Cible Prometheus indisponible
          description: La cible {{ $labels.job }} est indisponible depuis plus de 2 minutes.
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: up
              instant: true
              refId: A
          - refId: C
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: "-100"
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: "-100"
              expression: A
              refId: C
              type: threshold
